version: '2'
services:
    web:
        image: nginx:latest
        container_name: "nginx"
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
            - ./data/certs:/etc/nginx/certs
        networks:
            - code-network
    php:
        image: php:fpm
        container_name: "php-fpm"
        volumes:
            - ./code:/code
        networks:
            - code-network
    mariadb:
        image: mariadb:10.6
        container_name: "mariadb"
        restart: always
        volumes:
            - ./mariadb:/var/lib/mysql
            - ./mariadb/init.sql:/data/application/init.sql
        ports:
            - 3306:3306
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        networks:
            - code-network
        depends_on:
             - php
    redis:
        image: redis
        container_name: "redis"
        ports:
            - 6379:6379
        restart: always
        networks:
            - code-network
        depends_on:
             - php

networks:
    code-network:
        driver: bridge
